name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Get version from tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract changelog
        id: changelog
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"

          sed -n "/^## \[$VERSION\]/,/^## \[/p" CHANGELOG.md | sed '$d' | tail -n +2 > changelog_body.txt

          if [ ! -s changelog_body.txt ]; then
            echo "Release $VERSION" > changelog_body.txt
          fi

          echo "Extracted changelog:"
          cat changelog_body.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ env.VERSION }}
          body_path: changelog_body.txt
          files: |
            main.js
            manifest.json
          draft: false
          prerelease: false
          generate_release_notes: false